apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels: 
    app: nginx
    purpose: demo
spec:
  minReadySeconds: 10
  replicas: 3
  selector: 
    matchLabels: 
      app: nginx
  template:    
    metadata:
      name: nginx-pod
      labels: 
        app: nginx
        version: "1.25"
    spec:    
      containers:
        - name: webserver
          image: nginx:1.25
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            containerPort: 80
            protocol: TCP     

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc     
spec:
  selector: 
    app: nginx
    version: 1.25
  ports: 
    - name:
      port: 80
      targetPort: 80
      protocol: TCP 

